### ISSUE TITLE
problem with anvi-delete-hmms

### ISSUE THREAD

**Issue by tdelmont** [merenlab/anvio#1028]
I am on anvi'o master, and I observed a consistant bug with ```anvi-delete-hmms```:

When I delete Campbell_et_al and Rinke_et_al, then BUSCO_83_Protista is no longer available in the interface...

Best,

Tom

**Comment by ozcan** [comment]
I have tracked down this issue and found the reason but I think @meren should change this 

This issue caused by `completeness.py`, `get_best_matching_domain(self, d)` function.

```
        if len(set([d[0] for d in domain_specific_estimates])) == 1 or domain_specific_estimates[0][0] < 0.01:
            # clearly none of the domains match with any level of real confidence
            best_matching_domain, domain_matching_confidence = None, 0.0
        else:
            best_matching_domain, domain_matching_confidence = domain_specific_estimates[0][1], domain_specific_estimates[0][0]
```

So in case there is only one entry in `domain_specific_estimates` like `[(0.5421686746987951, 'eukarya')]` this function returns none because of the condition `len(set([d[0] for d in domain_specific_estimates])) == 1`, and I don't know the reason why, maybe it is intended to avoid case where multiple domains matches at 0.0?
