### ISSUE TITLE
genes database does not come with any state

### ISSUE THREAD

**Issue by xvazquezc** [merenlab/anvio#1038]
Hi there,

while dealing with #1033, I found a couple of things that are different in `master` compared to previous releases in `anvi-interactive --gene-mode`. Both cases perform as before with the base `anvi-interactive` so it's more than likely that it's due to some changes in the `--gene-mode` related code:

* In the header of the graphical output, the line containing the view info such as `Items order: Mean coverage (D: undefined; L: undefined) | Current view: mean_coverage | Sample order: custom`, it is completely missing.
* The output is not draw automatically any more.

Cheers,
Xabi

**Comment by meren** [comment]
I think the first thing is OK. It looks like this when I first run the interface:

![image](https://user-images.githubusercontent.com/197307/48843096-bb00d180-ed5b-11e8-8bc9-f5288710edb7.png)

And after clicking Draw, this is what it looks like:

![image](https://user-images.githubusercontent.com/197307/48843108-c653fd00-ed5b-11e8-8111-477cf13302ea.png)

The fact that it is not automatically drawing when the actual profile database has a state is because where in gene mode, the interactive interface is reading the states table not from the profile database, but from the genes database. I will now change the code to copy the states table from the profile database into the genes database, and ask you to take another look :)


Best,

**Comment by meren** [comment]
I think this is fixed now. I've been working on some key features in a branch, and I will now merge it to master, Xabi. I hope you can git pull `master` once it is ready, and continue playing with the gene databases. I will let you know when it is done.
