### ISSUE TITLE
Reporting the DNA sequence of the selected area on inspect window

### ISSUE THREAD

**Issue by ozcan** [merenlab/anvio#1087]

**Comment by meren** [comment]
Thank you very much for this, @ozcan :) Here is just a little request while it is fresh!

Currently it gives you this:

![image](https://user-images.githubusercontent.com/197307/51548433-ebcdb780-1e2d-11e9-9db8-d6ec6cd9808e.png)

I think it would have been more helpful if it gave the following in the window instead of what it shows now (so when you copy-paste, it immediately works for searching on NCBI etc):

```
>split_name range:x,y
ATCGATCG
```

if it is the entire split, it could simply give back:

```
>split_name
ATCGATCG
```


Best,

**Comment by meren** [comment]
Works like magic :) Thank you @ozcan!
