### ISSUE TITLE
Anvio-merge error with Auxiliary data

### ISSUE THREAD

**Issue by Leitemfa** [merenlab/anvio#1176]
Hello,

I was trying to perform anvio-merge but got the following error message 

`Auxiliary Data Error: The auxiliary database at "anvio/anvio-MPR3_3n_CUR/AUXILIARY-DATA.db" does not know anything about the split "NODE_1000_length_17421_cov_32.925429_split_00001"
`

Below you will find the version of anvi'o I am using:

`Anvi'o version ...............................: margaret (v5.5)
Profile DB version ...........................: 31
Contigs DB version ...........................: 12
Pan DB version ...............................: 13
Genome data storage version ..................: 6
Auxiliary data storage version ...............: 2
Structure DB version .........................: 1
`

**Comment by ozcan** [comment]
Hi @Leitemfa,

Thank you for reporting this and sorry for the late response, I think you are having this problem because of the `.` in the contig names. Anvi'o is usually pretty good at catching this kind of things early on and warn user but this might be an edge case. I will test this further and write you back.

Best,
