### ISSUE TITLE
File/Path Error

### ISSUE THREAD

**Issue by fetyj** [merenlab/anvio#1197]
Hello,
I'm trying to get pangenomic analysis for Lactobacillus plantarum from NCBI, then follow the tutorial here (http://merenlab.org/2019/03/14/ncbi-genome-download-magic/#processing-ncbi-genomes)
Problem, when I get to that part ``` anvi-run-workflow -w contigs -c contig.json ``` I got this error message 
```
Config Error: Well, the fasta.txt entry name contains characters that anvi'o does not like :/
              Please limit the characters to ASCII letters, digits, and the underscore ('_') 
              character
```
So I create a bash file as the example but now I get stuck with this kind of error
```
sh anvi.sh 
Input FASTA file .............................: /choppy/Lb_plant_anviopan/Lactobacillus_plantarum_16_GCF_000412205.1-contigs.fa
Name .........................................: Lactobacillus_plantarum_16_GCF_000412205.1
Description ..................................: No description is given
                                                                                                                                           

File/Path Error: You do not have permission to generate the output file                 
                 '/home/fiestaj/plantarum/Lactobacillus_plantarum_16_GCF_000412205.1.db'




File/Path Error: No such file:                                                             
                 '/home/fiestaj/plantarum/Lactobacillus_plantarum_16_GCF_000412205.1.db' :/
```
Any help would be great,
Thanks,

Fety
Anvi-profile
```
Anvi'o version ...............................: margaret (v5.4)
Profile DB version ...........................: 31
Contigs DB version ...........................: 12
Pan DB version ...............................: 13
Genome data storage version ..................: 6
Auxiliary data storage version ...............: 2
Structure DB version .........................: 1
```

**Comment by meren** [comment]
Hi @fetyj,

I am not sure if this error is associated with `v5.4` and fixed in `v5.5` because we do not have any other complaints about this workflow.

Please consider upgrading your anvi'o version to `v5.5` and try again. I apologize for the extra work, but we do not have the human resources to support older versions of anvi'o :)


Best wishes,

**Comment by fetyj** [comment]
Indeed, upgrading fix it! Thanks for the help :)

**Comment by AnaValero** [comment]
Hi,
First of all, congratulations and thanks for creating such great tool that I'm looking forward to use in my projects.

I'm having the same problem with anvio version 5.5.0 (installed yesterday), using the Spiroplasma data:
http://merenlab.org/data/spiroplasma-pangenome/

Once I run the following command:
`anvi-run-workflow -w pangenomics -c pan-config.json`

I get the following error:
> Config Error: Well, the fasta.txt entry name contains characters that anvi'o does not like :/
              Please limit the characters to ASCII letters, digits, and the underscore ('_') 
              character.

Here is my pan-config.json file after removing the character "-" from Spiroplasma-fasta.txt and leaving as Spiroplasma.txt (same error when using the exact names provided in the tutorial):
> {
    "fasta_txt": "Spiroplasma.txt",
    "project_name": "Spiroplasma",
    "external_genomes": "external_genomes.txt"
}

Do I also need to create a sh file? In such a case I have no clue which info it must contain and how to use.
Any help would be very much appreciated.

Best regards,
Ana

**Comment by meren** [comment]
Hi @AnaValero,

> Here is my pan-config.json file after removing the character "-" from Spiroplasma-fasta.

It is not complaining about characters in the file name. It is complaining about the `name` column in that file. If you look at the first column of the contents of this file, you should see names that match to what that Config Error says. There is a line in the workflow about that:

![image](https://user-images.githubusercontent.com/197307/64122096-4042f900-cd66-11e9-8374-8c03f8e44ac9.png)

If nothing makes sense, please send your `fasta_txt` file.

**Comment by AnaValero** [comment]
Hi,

Many thanks for your prompt reply. I've been working on the issue and it
seems that it was due to the command below, as the added name was
"Spiroplasma_MAG.fat". I changed it to "Spiroplasma_MAG" and the issue was
solved.

echo -e "Spiroplasma_MAG.fa\t`pwd`/MAGs/Spiroplasma_MAG.fa" \
                          >> Spiroplasma-fasta.txt


Afterwards I got different errors that I solved by setting up the COG
distribution (anvi-setup-ncbi-cogs) and running again the workflow. It was
then running for 12 hour approximately with no issues.

However, when I tried:

anvi-compute-ani -e external-genomes.txt \
                 -o ANI \
                 -p 03_PAN/Spiroplasma-PAN.db \
                 -T 6

It produced the following error message after being running for a couple of
hours:

(anvio5) ana@ana-Not-Specified ~/Desktop/MAGs $ anvi-compute-ani -e
external-genomes.txt -o ANI -p 03_PAN/Spiroplasma-PAN.db -T 6

CITATION
===============================================
Anvi'o will use 'PyANI' by Pritchard et al. (DOI: 10.1039/C5AY02550H) to
compute
ANI. If you publish your findings, please do not forget to properly credit
their
work.

[PyANI] Num threads to use ...................: 6
[PyANI] Alignment method .....................: ANIb
[PyANI] Log file path ........................: /tmp/tmpicz3jdoj

Genomes found ................................: 34
Temporary FASTA output directory .............: /tmp/tmpc1x6jk25
Output directory .............................: /home/ana/Desktop/MAGs/ANI

    [05 Sep 19 10:39:27 PyANI] Running ...



Config Error: PyANI returned with non-zero exit code, there may be some
errors. please check
              the log file for details.

--------------------------------------------

I've tried to find such log file within 00_LOGS folder unsuccessfully.
Also, I found in google that a user had the same error due to an old
version of python installed in his computer. I have Python 3.6 installed,
so I don't believe that it is my case.

Do you have any recommendation?
I'm afraid that I got stuck here.

Many thanks!!
Ana
