### ISSUE TITLE
Amino acid gene sequence includes codon that PRECEDES starting Met

### ISSUE THREAD

**Issue by ekiefl** [merenlab/anvio#1294]
In the following repro example, the gene sequence improperly includes the codon that precedes the starting ATG.

Make `reformatted.fa`:

```
>LOV
GGCATGGGCGAATTCTTGGCTACTACACTTGAACGTATTGAGAAGAACTTTGTCATTACTGACCCAAGATTGCCAGATAATCCCATTATATTCGCGTCCGATAGTTTCTTGCAGTTGACAGAATATAGCCGTGAAGAAATTTTGGGAAGAAACTGCAGGTTTCTACAAGGTCCTGAAACTGATCGCGCGACAGTGAGAAAAATTAGAGATGCCATAGATAACCAAACAGAGGTCACTGTTCAGCTGATTAATTATACAAAGAGTGGTAAAAAGTTCTGGAACCTCTTTCACTTGCAGCCTATGCGAGATCAGAAGGGAGATGTCCAGTACTTTATTGGGGTTCAGTTGGATGGAACTGAGCATGTCCGAGATGCTGCCGAGAGAGAGGCCGTCATGCTGGCCAAGAAAACTGCAGAAGAGATTGATGAGGCGGCATGANNN
```

```
anvi-gen-contigs-database -f reformatted.fa -o GENE_SEQ_STARTS_WITH_X.db
open GENE_SEQ_STARTS_WITH_X.db
```

Browse the `gene_amino_acid_sequences` table.

This creates undesirable downstream effects, for example, causes KeyError in `anvi-gen-structure-database`

**Comment by meren** [comment]
:(

I think the best we can do is to report that this is what's happening, and do not proceed with this gene for structure DB (if they say `--just-do-it` we can trim the gene to the start codon on-the-fly with a warning perhaps?).

It is indeed frustrating, but if that's what the gene caller reports, or the user defines as a gene with their external gene calls, then we have to stick with it. but it would be better if anvi'o throws a warning or an exception instead of exploding with a traceback.

**Comment by ekiefl** [comment]
I agree.

I handle it with the following commits. There is now a utils fn to test if a gene sequence is 'clean'.

2483252d9c1fbfa4d816d4dd6101657722e40a1d
3b45394b753a2335f13b33fe5dd8a005003eeda2
4cc971d01ecf3881618166a4ec9ae9ec83f0e1ec
