### ISSUE TITLE
design of anvi-export-gene-coverage-and-detection

### ISSUE THREAD

**Issue by qinglong89** [merenlab/anvio#1405]
Hello,

I am still not quite clear about the design of anvi-export-gene-coverage-and-detection. Here I am talking about the combined analysis of paired metagenomic and metatranscriptomic data in anvio.

For RNA-seq in single bacteria experiments, FPKM or TPM is used as another type of "coverage" data for downstream interpretation. For both single RNA-seq and metagranscriptomic seq, we usually provide similar amount of total RNAs from Control and Treatment samples for sequencing; so per million is usually performed for scaling in single RNA-seq analysis. However, metatranscriptomics involves multiple organisms in the samples, so should we normalize FPKM or TPM values of the gene with the coverage of its corresponding metagenomic bin? 

Thanks.

**Comment by FlorianTrigodet** [comment]
Hello,

I had the same question a few months ago when working with metatranscriptomic data. I strongly agree with you that the normalization should be perform at the bin level, and not at the whole sample with multiple organisms with different abundances.

I used DEseq2 for the normalization (and differential expression analysis), but the principle is the same with FPKM or TPM. 

The anvi'o command `anvi-export-gene-coverage-and-detection` provides coverage and detection, but **not the reads counts**, which is required for FPKM, TPM, DESeq2. Currently, there are no anvi'o command to get the read count per genes. 

You could alway export all genes from a contig db (your metagenome) with `anvi-get-sequences-for-gene-calls` and use a pseudo mapping software like [Salmon](https://salmon.readthedocs.io/en/latest/salmon.html), which give the number of reads mapping to a gene. 

Since you binned your metagenome, you have a bin collection that can be summarized with `anvi-summarize`. In the summary directory, and for every bin, there is a file with the genes calls present in that bin. I used that information to normalize the read counts from Salmon for every bin. 

Florian

**Comment by FlorianTrigodet** [comment]
Maybe we could improve anvi'o for metatranscriptomics with a command that would directly give the reads count per gene call for a collection of bin.
The output would look like this:

gene_call | bin_name | count
-- | -- | --
0001 | Bin_1 | 10
0002 | Bin_1 | 0
0003 | Bin_2 | 24

Then one could normalize the counts for every bins.

**Comment by qinglong89** [comment]
> I used that information to normalize the read counts from Salmon for every bin

Thanks Florian! To clarify, you mean you normalize the read count of gene with the mean coverage of its corresponding bin? Also the bin coverage has been already normalized based on the number of total mapped reads across samples during anvi-merge step, are you able to clarify this as well if such bin coverage is used for meta-RNA-seq analysis?

**Comment by FlorianTrigodet** [comment]
Hi, 

No, I am not using the coverage of the corresponding bin. In brief, if I have N bins, I want to perform N normalizations. For each bin, you have a set of genes + corresponding reads count, and you can use the sum of reads per bin to compute the FPKM or TPM.
Does that make sense?

Florian

**Comment by qinglong89** [comment]
> Does that make sense?

Yes, make sense!
Thanks!
