### ISSUE TITLE
[BUG] Performance issue with anvi-run-hmms

### ISSUE THREAD

**Issue by FlorianTrigodet** [merenlab/anvio#1605]
## Short description of the problem

`anvi-run-hmms` is taking too long for a single genome.

## anvi'o version

```
Anvi'o version ...............................: esther (v6.2-master)
Profile DB version ...........................: 35
Contigs DB version ...........................: 20
Pan DB version ...............................: 14
Genome data storage version ..................: 7
Auxiliary data storage version ...............: 2
Structure DB version .........................: 2
Kegg Modules DB version ......................: 2
tRNA-seq DB version ..........................: 1
```

## System info

Using the github main branch, on Linux.

## Detailed description of the issue

`anvi-run-hmms` has been running for more than 16 hours (5 threads) for a single genome of ~3 Mbp. And that's a lot of time for a single genome.

```
HMM sources ..................................: Ribosomal_RNA_16S,
                                                Ribosomal_RNA_28S,
                                                Ribosomal_RNA_18S, Protista_83,
                                                Ribosomal_RNA_23S, Bacteria_71,
                                                Archaea_76, Ribosomal_RNA_5S,
                                                Ribosomal_RNA_12S
Alphabet/context target found ................: RNA:CONTIG
Alphabet/context target found ................: AA:GENE

HMM Profiling for Ribosomal_RNA_16S
===============================================
Reference ....................................: Seeman T,
                                                https://github.com/tseemann/barrnap
Kind .........................................: Ribosomal_RNA_16S
Alphabet .....................................: RNA
Context ......................................: CONTIG
Domain .......................................: N/A
HMM model path ...............................: /tmp/jobs/7858271/tmphewx3_99/Ribosomal_RNA_16S.hmm
Number of genes in HMM model .................: 3
Noise cutoff term(s) .........................: --cut_ga
Number of CPUs will be used for search .......: 5
HMMer program used for search ................: nhmmscan
Temporary work dir ...........................: /tmp/jobs/7858271/tmpw84815_j

WARNING
===============================================
You requested 5 cores but there were only a single sequence in the FASTA file
for the target 'RNA:CONTIG'. Anvi'o will use a single process with 5 cores
instead. And that's that.

Log file for thread 0 ........................: /tmp/jobs/7858271/tmpw84815_j/RNA_contig_sequences.fa.0_log
[21 Dec 20 18:49:09 Processing] Running hmmscan in 5 threads...
```

**Comment by FlorianTrigodet** [comment]
I can also see other `anvi-run-hmms` that have been running for more than 6 days (5 threads) on the same server, and for single genome also.

**Comment by ivagljiva** [comment]
This is concerning, especially considering there is only one target sequence.
```
You requested 5 cores but there were only a single sequence in the FASTA file
for the target 'RNA:CONTIG'. Anvi'o will use a single process with 5 cores
instead. And that's that.
```

I wonder if there is a bug in this case which is causing it to hang.

**Comment by ivagljiva** [comment]
This is where that warning is coming from in our `hmmer.py` driver:
```
    num_parts = len(self.target_files_dict[target])
        cores_per_process = 1
        if num_parts < self.num_threads_to_use:
            cores_per_process = self.num_threads_to_use // num_parts

            self.run.warning(f"You requested {P('core', self.num_threads_to_use)} but there were only {P('sequence', num_parts)} "
                             f"in the FASTA file for the target '{target}'. Anvi'o will use {P('process', num_parts, suffix_for_plural='es')} "
                             f"with {P('core', cores_per_process)} instead. And that's that.")

```
The warning states that we will use a single process with 5 cores instead of 5 threads with 1 core each, but there is nothing in that `if` clause that actually changes the number of threads. That makes me think that we are instead running 5 threads (with 5 cores each), and that 4 of those have nothing to do because there is no input, so they are hanging.

This bug is likely my fault, as I was changing the multithreading in this file last week but I didn't test this case. I will try to fix it now.

**Comment by ivagljiva** [comment]
## Reproduce the bug

```
anvi-get-sequences-for-hmm-hits -c ISOLATE_CONTIGS.db --hmm-sources Ribosomal_RNAs --gene-names Bacterial_16S_rRNA -o test-16S-sequences.txt
head -n 14 test-16S-sequences.txt > one_sequence.fasta
anvi-script-reformat-fasta --simplify-names one_sequence.fasta -o one_sequence_reformatted.fasta
anvi-gen-contigs-database -f one_sequence_reformatted.fasta -o 16S_test.db
# weirdly, prodigal took that one sequence and identified 2 gene calls
anvi-run-hmms -c 16S_test.db -T 5
```
I ended up with two gene calls in the test database, but regardless we can trigger this case by giving it 5 threads:
![image](https://user-images.githubusercontent.com/10360586/102925824-b5ee3f00-4459-11eb-8ad2-41359cfef45d.png)

It has been going at it for about 15 minutes, way too long for just 2 gene calls, so I think that is enough to say it is hanging.

In contrast, if you run the same command but with just one thread, it finishes blindingly fast. So the problem is in fact with the case where you have fewer sequences than threads.

## Bug Fix

The issue is not exactly what I guessed before. We only spawn one thread for each partial input file, so we are not running threads without input. However, we wait for `self.num_threads_to_use` to finish - and as I mentioned above, this variable is not reset properly in this case. I fixed this by adding `self.num_threads_to_use = num_parts` to the `if` clause, and now running `anvi-run-hmms -c 16S_test.db -T 5 --just-do-it` works blindingly fast as it should.

@FlorianTrigodet and @mschecht you should kill your currently running `anvi-run-hmms` jobs and restart them. Please let me know if they continue to take too long.

**Comment by meren** [comment]
Thank you for figuring this one out and fixing it, Iva :)
