### ISSUE TITLE
[BUG] anvi-setup-kegg-kofams fails on sqlite3 error

### ISSUE THREAD

**Issue by VibrantStarling** [merenlab/anvio#1708]
## Short description of the problem
kegg kofams database set up fails due to "database is locked" error in sqlite3

## anvi'o version 7
anvi-self-test runs smoothly, no problems here.
Initially on set up I had to completely reinstall scikit-learn because it didn't set itself up properly and was missing cython. The instructions to use setup.py just did not work. 

## System info
Debian 7 on a remote linux server

## Detailed description of the issue
I ran anvi-setup-kegg-kofams for the first time, expecting it to just get on with it and sort itself out. Nothing fancy, just used defaults. Here is a screenshot of the code:

![image](https://user-images.githubusercontent.com/47856505/114043576-50925280-987e-11eb-9631-639c7445ce7a.png)

**Comment by ivagljiva** [comment]
@VibrantStarling , sorry you are having an issue. I've never seen this error from `anvi-setup-kegg-kofams` before, but this kind of issue should only happen if the `MODULES.db` database was opened previously and not closed properly, which would not be the case when you are running this program for the first time, or if too many threads are trying to access this database at the same time (but `anvi-setup-kegg-kofams` is single-threaded, so it should not be the case here).

Regardless, I have a few ideas for what you can try to fix this, or at least to figure out what is going wrong. First, just try to run it again using `anvi-setup-kegg-kofams --reset`. The `--reset` flag will make sure the previous copy of the KEGG data will be deleted, before the program downloads and sets it up again. (I saw in your command that you already tried the `--reset` flag, but it doesn't look like any existing folder was removed - possibly because it was your first time running the program and there was nothing to remove).

If you get the same error doing that, I would like you to try removing the previous KEGG data directory manually. Based on the paths in the error traceback, it is probably located on your computer at `/pub28/helend/miniconda3/envs/anvio-7/lib/python3.6/site-packages/anvio/data/misc/KEGG` (please double check this path before you remove it). So you would run 
```
rm -r /pub28/helend/miniconda3/envs/anvio-7/lib/python3.6/site-packages/anvio/data/misc/KEGG
``` 
to get rid of that folder manually. Then, please download the KEGG datapack manually using
```
wget https://ndownloader.figshare.com/files/25878342 -O KEGG_build_2020-12-23_45b7cc2e4fdc.tar.gz
```
That command will put the KEGG archive file into your current working directory, and then you can try to run the setup from that data directly:
```
anvi-setup-kegg-kofams --kegg-snapshot KEGG_build_2020-12-23_45b7cc2e4fdc.tar.gz
```

Please let me know whether or not either of these solutions work for you.

**Comment by VibrantStarling** [comment]
Something there worked! The third command didn't though I had to do this:

![image](https://user-images.githubusercontent.com/47856505/114056390-8426aa00-9889-11eb-9b06-d8e6f50ff099.png)

Thanks

**Comment by ivagljiva** [comment]
Excellent :) I'm happy that anvi'o was able to help you with the right command, even better than I could ;)
