### ISSUE TITLE
[FEATURE] Anvi'o interactive interface should check for submodules

### ISSUE THREAD

**Issue by meren** [merenlab/anvio#1719]
## The need

Instead of welcoming the user with a never ending wait screen that confuses users who track the active codebase (i.e., #1717), the anvi'o interactive interface should give a non-cryptic error message if some of the JavaScript libraries we use through submodules are missing.

## The solution

Remove all submodules, see what the interface says when initiated.

## Beneficiaries

Everyone who tracks the active codebase without initializing submodules for interactive interface.

**Comment by matthewlawrenceklein** [comment]
@meren A very basic fix would be to attach the `onerror` attribute to any/all of the lib dependency script calls in `index.html`, and set the value to an inline `alert('some message here')`
![Screen Shot 2021-04-16 at 2 07 25 PM](https://user-images.githubusercontent.com/62408216/115072415-316a7500-9ebd-11eb-8011-0ac313e0cd4c.png)

On the plus side, this options doesn't require changing the order of how `index.html` loads dependencies since we're not relying on any of our js, or other dependencies like Toastr. On the other hand, The issue noted in #1717 would result in serial alert messages for each failed load, which sounds infuriating. 

We can alternately point each `onerror` attribute to a js function we define in `main.js`. On the plus side, this allows for slightly less abrasive error handling. Conversely, `main.js` would need to be loaded prior to any of the library dependencies, and I'm not sure what implications that would have beyond this issue. 

![Screen Shot 2021-04-16 at 1 55 36 PM](https://user-images.githubusercontent.com/62408216/115072504-4f37da00-9ebd-11eb-8bf5-a3f82014f3ac.png)

**Comment by meren** [comment]
I like the second option better but perhaps we can add a new file, i.e., `js/error.js` to not have to change the order of anything else?

**Comment by matthewlawrenceklein** [comment]
@meren Do we want our error messaging to offer specific recourse a la #1717 `git submodule update --init`, or should the message simply warn about failed dependency loads and make no other assumptions?
`

**Comment by meren** [comment]
I think we can simply warn about failed dependencies and then include something like "If you are tracking the active codebase, did you remember to run  `git submodule update --init`?".

Anvi'o philosophy is to try to help users when things fail :)

**Comment by meren** [comment]
#1724 solves this.

**Comment by meren** [comment]
Scratch that. When I manually get rid of my `bootstrap-sortable` module directory in the codebase and run `anvi-interactive` on a project, this is what I get in my terminal along with a never-ending loading in the screen, @matthewlawrenceklein:

![image](https://user-images.githubusercontent.com/197307/116110747-95d6c280-a67b-11eb-81f4-59c7ed59b4d3.png)

**Comment by matthewlawrenceklein** [comment]
@meren `bootstrap-sortable` is loaded separately (`index.html` ln 66) and after the main block of submodule calls (ln 25-40) and js files (ln 42-63). 

`bootstrap-sortable` can be added to the new error messaging implementation, but can also potentially trigger a toastr warning if preferable. 

Similarly, the `marked` and `bootstrap-markdown` dependencies can follow suit.

**Comment by meren** [comment]
I am not sure what is the best solution here, @matthewlawrenceklein. But if the goal is to make missing submodules do not end up crashing the interface, the current solution is not working.

**Comment by matthewlawrenceklein** [comment]
addressed in PR #1724
