### ISSUE TITLE
Exporting annotations from Anvio. Plans?

### ISSUE THREAD

**Issue by VibrantStarling** [merenlab/anvio#1764]
Hello

I've been messing about with annotations in anvio and have realised you don't really have a method of exporting them. Is this something you're working on?
I know you have an export gff function, but all the genes start at position 1 and are also unnamed with their actual annotation or annotation source.

I'd love to see something implemented for this if it's possible. It would be so useful to be able to take the genomes all the way through from fasta to pangenome to a fully annotated genome that's ready for submission to genbank or embl

**Comment by meren** [comment]
Hey @VibrantStarling,

Sorry for the late response to this!

> I know you have an export gff function, but all the genes start at position 1 and are also unnamed with their actual annotation or annotation source.

We addressed the gene caller error in the active branch (that was mentioned in #1744).

> I'd love to see something implemented for this if it's possible. It would be so useful to be able to take the genomes all the way through from fasta to pangenome to a fully annotated genome that's ready for submission to genbank or embl

I agree that it would be great to have something that reports rich output files for NCBI or EMBL submissions. We don't have it because no one asked for it so far, we have been using `anvi-export-*` programs for most of our needs, and we do not have much experience with NCBI or EMBL submissions to make sure what we implement is actually useful/accurate.

Perhaps one day someone who has the experience and need will help us develop a tool, and we will be more than happy to help them find what they need in the codebase :)
