### ISSUE TITLE
[FEATURE] Updating GTDB to the latest release 06-RS202

### ISSUE THREAD

**Issue by rzhan186** [merenlab/anvio#1793]
Dear Anvio developers, 

I am hoping that the `anvi-setup-scg-taxonomy` could implement the latest GTDB release, which is 06-RS202. The current version of GTDB is r95. 

It seems this script would need to be modified [https://github.com/merenlab/anvio/blob/master/anvio/data/misc/GTDB-RELEASES.yaml ](URL). 

Please let me know if there is anything I can help with. Thank you! 

Rui

**Comment by meren** [comment]
Thanks, @rzhan186. I'm looking into this :)

**Comment by meren** [comment]
Hey @rzhan186, thank you for this. It is now done. Took a bit because Pierre at the GTDB needed to fix something in the marker gene FASTA file deflines the latest release distributed.

You should be able to `git pull`, re-run `anvi-run-scg-taxonomy` on your contigs databases if you want, and everything should work smoothly.

Please let me know if they don't.


Best wihses,
