### ISSUE TITLE
how to create BAM file for profile.db creation when working with assemblies

### ISSUE THREAD

**Issue by spencer411** [merenlab/anvio#1802]
I am using anvi'o to look at the pan-genome of ~170 bacterial isolates. I have had no problem installing and getting my data into anvio, but now I am at a point where I would like to calculate pN/pS across all my genes. To do so it looks like I will need a profile-db file for each of my contigs-db files. Which apparently means I will need BAM files to create a profile.db files, but where does that BAM file come from? 

Each of my genomes were assembled with shovill, and then I created contigs-db files directly from each assembly using the directions on the anvio website. Is there a way to go back and create a BAM file for this process? 

Any help or explanation is appreciated.

**Comment by ivagljiva** [comment]
Hi @spencer411 , sorry that your question has gone unanswered for so long. I assume you have long since moved on, but just in case you are still looking for help with this: a BAM file contains alignments of sequencing read to a reference sequence. Its the binary version of a SAM file, which is the output of read recruitment software like `bowtie2` or `BWA`.

To get a BAM file matching to the sequences in your contigs database, you would run a read recruitment software on the fasta file containing those contigs (making sure that the contig names match between the fasta file and the contigs db), convert the file to BAM with `samtools`, and then sort/index the BAM file (possible with `anvi-init-bam`). The resulting BAM could be used as input to `anvi-profile`. 

For more information, you could check out https://anvio.org/help/8/artifacts/bam-file/ and the pages that are linked from that one.
