### ISSUE TITLE
anvi-refine crashing because the MAG is too big to load

### ISSUE THREAD

**Issue by ARBramucci** [merenlab/anvio#1824]
Is there a way to fix this issue of having a MAG that is way too big (82.89 Mb) but I can't even split it into multiple bins because it crashes the online server when I try to make a bin.
I am very new with ANVIO so I am sorry if this is a simple issue.
I am using a macOS Catalinia 16GB memory
## anvi'o version
anvio-7
Thanks so much for any suggestions
Anna B

here is my self test

```
Anvi'o .......................................: hope (v7)

Profile database .............................: 35
Contigs database .............................: 20
Pan database .................................: 14
Genome data storage ..........................: 7
Auxiliary data storage .......................: 2
Structure database ...........................: 2
Metabolic modules database ...................: 2
tRNA-seq database ............................: 1
```

**Comment by ARBramucci** [comment]
Sorry I mean the interactive interface that ANVIO brings up when you are running anvi-refine

**Comment by meren** [comment]
Probably there are too many splits for that MAG to be visualized in the interface, @ARBramucci. Sorry. It should tell you somewhere in the output logs of `anvi-refine` how many there are. If you see a number that is larger than 25,000, the hierarchical clustering step will likely fail due to its computational complexity.

There is a program called `anvi-split`, but probably you will not be able to import a meaningful collection into your profile database for that MAG.

Sorry.
