### ISSUE TITLE
[BUG] SQLite lock when importing taxonomy into contigs database with Centrifuge

### ISSUE THREAD

**Issue by gus-mri-thomas** [merenlab/anvio#1854]
## Short description of the problem

I've generated a centrifuge report, centrifuge.tsv, and a contigs.db - but when executing the `anvi-import-taxonomy-for-genes` command, the SQL3 database tells me that it's locked.

## anvi'o version

Anvi'o .......................................: hope (v7.1)

Profile database .............................: 38
Contigs database .............................: 20
Pan database .................................: 15
Genome data storage ..........................: 7
Auxiliary data storage .......................: 2
Structure database ...........................: 2
Metabolic modules database ...................: 2
tRNA-seq database ............................: 2

## System info

I'm running Ubuntu 20.04, and followed the standard installation instructions for anvi'o.
I completed your user tutorial for Metagenomics, and have successfully launched anvi-interactive.

## Detailed description of the issue

Following instructions to import taxonomy to an anvi'o database using Centrifuge, found at [(https://merenlab.org/2016/06/18/importing-taxonomy/)], I first generated a `gene-call.fa` file, and successfully imported an indexed Centrifuge database. I ran the  `centrifuge -f -x ` command and got back both the `centrifuge_report.tsv` and `centrifuge_hits.tsv`. During the final step of the process, while executing `anvi-import-taxonomy-for-genes`, I received the following traceback:
```
File "/home/gthomas/.conda/envs/anvio-7.1/bin/anvi-import-taxonomy-for-genes", line 82, in <module>
    main(args)
  File "/home/gthomas/.conda/envs/anvio-7.1/bin/anvi-import-taxonomy-for-genes", line 54, in main
    tables_for_taxonomy.create(genes_taxonomy_dict, taxon_names_dict, args.parser)
  File "/home/gthomas/.conda/envs/anvio-7.1/lib/python3.6/site-packages/anvio/tables/taxonomy.py", line 99, in create
    self.populate_taxon_names_table()
  File "/home/gthomas/.conda/envs/anvio-7.1/lib/python3.6/site-packages/anvio/tables/taxonomy.py", line 45, in populate_taxon_names_table
    database.disconnect()
  File "/home/gthomas/.conda/envs/anvio-7.1/lib/python3.6/site-packages/anvio/db.py", line 323, in disconnect
    self.conn.commit()
sqlite3.OperationalError: database is locked
```
Unfortunately, I am not at liberty to share the contigs.db I am using.

**Comment by meren** [comment]
Hey @gus-mri-thomas, this is a very low-level error coming from the SQLite herself. If the database is locked, it is locked. Which means either another process is working on it, or there is a problem with it. In either case, anvi'o can't do anything here sadly :(

**Comment by gus-mri-thomas** [comment]
By "there is a problem with it", is it not implied that the problem is within anvi'o? The database is generated by your own metegenomics workflow, after all. I may be speaking from a place of ignorance, given that I have only cursory knowledge/experience with SQLite - but, what other process could possibly be working on the database? I don't have anvi-interactive or any other anvi command operating on it.

**Comment by gus-mri-thomas** [comment]
https://stackoverflow.com/questions/3172929/operationalerror-database-is-locked
Yeah ... for anyone else reading this, it most certainly seems as if this problem stems from Anvi'o. If SQLite can't support whatever these anvi commands are doing, then reformatting of how taxonomy is imported ... or how COGS can be run on a contigs.db for that matter (where I had a similar problem), must be done.

From the stack:
   " SQLite is meant to be a lightweight database, and thus can't support a high level of concurrency. OperationalError: database is locked errors indicate that your application is experiencing more concurrency than sqlite can handle in default configuration. This error means that one thread or process has an exclusive lock on the database connection and another thread timed out waiting for the lock the be released.
    Python's SQLite wrapper has a default timeout value that determines how long the second thread is allowed to wait on the lock before it times out and raises the OperationalError: database is locked error.
    If you're getting this error, you can solve it by:
        **1. Switching to another database backend. At a certain point SQLite becomes too "lite" for real-world applications, and these sorts of concurrency errors indicate you've reached that point.
        2. Rewriting your code to reduce concurrency and ensure that database transactions are short-lived.
        3. Increase the default timeout value by setting the timeout database option**"

**Comment by meren** [comment]
> Yeah ... for anyone else reading this, it most certainly seems as if this problem stems from Anvi'o.

I am reading this, @gus-mri-thomas, but my original answer remains. I really don't see it as an anvi'o problem. Anvi'o developers respond to a large number of user requests each week. As this is something we do voluntarily by taking time from our own research, we often have to be succinct in our responses to ensure maximum efficiency. But let me try to better explain myself.

Every week our group alone runs thousands of database operations on hundreds of databases if not more using the metagenomics workflow. We are not the only group that uses anvi'o, either. But we never hear about database locked errors. So this is a novel problem, and based on everything I know from your report it is specific to you (i.e., specific to your project, your computer system, or your way of running anvi'o). It doesn't matter which one it is. What matters is, we can't solve it by changing anvi'o.

It is difficult to predict what might have happened. There are multiple ways to get an anvi'o database stuck in a locked state. For instance, if someone runs `anvi-run-hmms`, `anvi-run-ncbi-cogs` and `anvi-scan-trnas` on the same database in parallel, at least one of these processes will die by complaining that the db is locked. Or, more likely, if any program that opened the database with write access dies, for instance because their HPC run out of memory in the middle of the write operation, every downstream SQLite access to that database will die with the same complaint. Anvi'o does not cause broken databases itself (because it creates and operates on many of them every day), but anvi'o databases do seldom break. But just because it can happen does not automatically mean that it must have something to do with the programming of anvi'o.

For full disclosure, although I don't see it from what you've sent, this STILL could be an anvi'o problem for some mysterious reason just like a flat tire may be Toyota's fault for some mysterious reason. But given (1) the total evidence you have provided me with, (2) the fact that I hear about this problem the first time, and (3) you are not funding anvi'o developers to go after mysterious problems (smiley), the extent of help we can offer from these pages on this particular issue will unlikely  go beyond my original answer.

For the lack of a better analogy, a locked database is not an anvi'o problem as a flat tire is not a Toyota problem. Imagine that I'm an engineer in Toyota and someone tells me that their car refuses to leave the parking lot due to a flat tire. They will have my sympathy, and I will even feel upset that something that I have contributed has ruined their day. But it doesn't change the fact that Toyota will not be able to do anything to avoid flat tires, even if a Toyota engineer is kindly -and somewhat ironically- provided with an article on flat tires from DriversUnited dot com that has zero useful information for a Toyota engineer to learn how to make a better car.

If you continue your investigation and identify why is this happening perhaps with the help of others, please feel free to send a Pull Request and I will personally study it.

Best wishes,
