### ISSUE TITLE
[DISCUSSION] Polishing the pangenome using Anvio workflow

### ISSUE THREAD

**Issue by Emmasw** [merenlab/anvio#1919]
I have been following your tutorial for polishing the pangenome (https://merenlab.org/data/spiroplasma-pangenome/). 
Although, there are two functions that I cannot find when following the guide in Anvio interface, namely: 

•	Select ‘SCG_Phylogeny’ from Settings > Layers > Order by combo box to order genomes by the phylogenomic tree
•	Use Settings > Main > Layers to increase genome / group distances using the margin column
 
Can anyone help me here?

**Comment by ivagljiva** [comment]
Hi @Emmasw, I am sorry that this issue has gone unanswered for over a year. I guess it is probably unlikely that you are still looking for help at this point, but just in case:

- I think it is likely that `SCG_Phylogeny` needs to be imported as a layer order. It looks like there is a command for that in the previous section of the tutorial:
```
# import the layers order file
anvi-import-misc-data -p 03_PAN/Spiroplasma-PAN.db \
                      -t layer_orders 03_PAN/Spiroplasma-phylogenomic-layer-order.txt
```
maybe it didn't work, and that is why you couldn't find it in the layers order box.

- the margins column should be there when you look at the Layers section in the main page on the left side, so I'm not sure why you don't see them. It is the same section where you have the color boxes.

- it is also possible that the interface layout/options were moved (since this tutorial is from v5.5), but these are central functions so I think it is unlikely

Again, sorry for the delay. I am closing this issue now, but feel free to reopen it if your questions are not answered.
