### ISSUE TITLE
[BUG] anvi-get-codon-frequencies with synonymous flag introduces empty fields in table

### ISSUE THREAD

**Issue by dspeth** [merenlab/anvio#1978]
## Short description of the problem

When running `anvi-get-codon-frequencies` with `--synonymous` codons encoding amino acids that do not occur in the predicted protein sequence are assigned a blank field instead of a 0.0 value. Not sure if this is the intended behaviour to distinguish the two, but the presence of NA values can break downstream processing.
 
## anvi'o version

development version on linux, installed with conda

## System info

Linux, debian 9

## Detailed description of the issue

I understand the value of being able to distinguish a 0.0 (the codon doesn't occur, but the AA does) and 0.0 (the codon doesn't occur because the amino acid doesn't), but for my purpose it wasn't necessary. Happy to share files if needed

**Comment by semiller10** [comment]
In the calculation of synonymous relative frequencies, NA is caused by 0/0 when the amino acid is absent from the sequence. Replacement of NA with 0.0 will skew codon usage bias and other metrics based on this data. Since I trust that the user knows what they're doing given sufficient warning, I've added a new flag, `--infinity-to-zero`, that does what you want, replacing all NA values that occur in output tables. The flag should only have an effect with `--synonymous`, the only context in which NA should occur. Thanks for the input, @dspeth!

(For main change to codebase and tests, see [flag to replace missing values caused by missing amino acids in synon…](https://github.com/merenlab/anvio/commit/09ed2660be032202f63ff999d8b7eadafe2ea1a9))
