### ISSUE TITLE
[BUG] Support values can be misplaced in the interactive interface

### ISSUE THREAD

**Issue by tdelmont** [merenlab/anvio#2043]
## Short description of the problem

Support values in the interactive interface can be wrong, due to a well known problem.

 
## anvi'o version

anvi'o v7.1

## System info

Mac

## Detailed description of the issue

We realised that bootstrap values can be misplaced in the interactive interface. This is especially true when playing around with re-rooting. This is a well know phenomenon, described in this paper: https://academic.oup.com/mbe/article/34/6/1535/3077051

## Files to reproduce

Here is are files that can be used for testing:
[Archive.zip](https://github.com/merenlab/anvio/files/10694187/Archive.zip)

**Comment by meren** [comment]
You are the best, Tom. Thank you for reproducible examples.

**Comment by meren** [comment]
I hope you would be available for questions later, too.

**Comment by metehaansever** [comment]
I can't see all the things in the Branch Support section.
I try with that piece of command:

`anvi-interactive --manual -p PROFILE.db -t DNApolB_NCLDV_marine_db_v1.Darius_EukaOnly_exceptAlpha.wMedusa.noLB5.Duplodna.Baculo.nr95.corrected.removedSeqTreemmed_Tom.noLoneSeq2.fftnsi.trim50.fa.treefile -d metadata_duplodna.txt 
`

![Screenshot from 2023-02-09 11-50-49](https://user-images.githubusercontent.com/24258998/217792575-88ce1864-2412-4438-ab29-ed7e9de4ed9f.png)

**Comment by tdelmont** [comment]
You should be able to see the support values using the mouse (right side of the interface) and pointing it to the branche splits within the tree. 

The problem is that the scores provided by anvi'o do not necessarily match to those in the tree itself (named DNApolB_NCLDV_marine_db_v1.Darius_EukaOnly_exceptAlpha.wMedusa.noLB5.Duplodna.Baculo.nr95.corrected.removedSeqTreemmed_Tom.noLoneSeq2.fftnsi.trim50.fa.treefile)

**Comment by tdelmont** [comment]
I just understood. In our case, we have 2 support values and because of that none are displayed, which is for another request.
But again, what we have done is explore the values using the mouse in the tree, interactively. 

Sorry, since all our work is done using 2 support values, I do not have a better example for you.

**Comment by metehaansever** [comment]
> You should be able to see the support values using the mouse (right side of the interface) and pointing it to the branche splits within the tree.
> 
> The problem is that the scores provided by anvi'o do not necessarily match to those in the tree itself (named DNApolB_NCLDV_marine_db_v1.Darius_EukaOnly_exceptAlpha.wMedusa.noLB5.Duplodna.Baculo.nr95.corrected.removedSeqTreemmed_Tom.noLoneSeq2.fftnsi.trim50.fa.treefile)

I guess there is something else because all the support values looks **0**.
![Screenshot from 2023-02-09 13-56-25](https://user-images.githubusercontent.com/24258998/217819100-e3d77cd1-e3bd-46b3-a073-fb58ace069d4.png)
Maybe we can turn this bug into a feature. We can show 2 support values on the Mouse Layer.
What you think about that? @meren

**Comment by meren** [comment]
I see. There are two problems here:

* One, anvi'o doesn't know how to show multiple branch support values (I mean, it is calling it 'label' in the interface, when `97.1/97` is *not* the label, but it is two branch support values of `97.1` and `97`).
* Two, anvi'o shifts these values, i.e., `97.1` and `97` is not even the correct value to show for that particular branch.

I think we need a very simple phylogentic tree with made-up values and branch names that would help us solve the second first, and then we can implement something to show multiple branch support values properly :)

**Comment by tdelmont** [comment]
Correct, this bug report is for the second issue, which is more problematic and very likely also occurs for people having one single support value.
Again, I do not have trees with single values as of now....

Tom

**Comment by FlorianTrigodet** [comment]
Very interesting paper! And probably so many mislabelled trees out there.
The main problem is the newick tree format doesn't have a way store branch support values. You can only annotate nodes, and implicitly it is assumed that the value is for the branch above, toward the root. But when you reroot, some branches are now upside down, and the node annotation is used to describe a wrong branch. 

I made a small test case based on that paper (it is a newick tree, but I called it .txt because github was not happy). 
[tree.txt](https://github.com/merenlab/anvio/files/10698539/tree.txt)

```bash
anvi-interactive --manual -t tree.txt -p PROFILE.db
```

Here is what we see without rooting. Everything is fine:
![Screenshot 2023-02-09 at 4 15 39 PM](https://user-images.githubusercontent.com/10922896/217853819-08a5815b-a53a-4b5a-b929-3cc1afb59086.jpg)

Now reroot from X and it looks like this now. On the A panel you see anvi'o output, and on the B panel you see what it should be. Funny the "0", it correspond to the initial "root" from the figure above".

![Screenshot 2023-02-09 at 4 23 18 PM](https://user-images.githubusercontent.com/10922896/217861280-d8d0f06f-8d6d-434c-a8d2-281d9ae550ca.jpg)


An internal node (not root, not tip) always have three branches right? To know for which branch your support value is for, you should look for the branch leading to the original root of your newick file. Without re-rooting, it implicitly means the branch above.

**Comment by FlorianTrigodet** [comment]
Another issue arise. What is your node's comment are not branch value, but it means something else, actually for the node? 

Then we need a check box in the additional setting asking the user if the node's annotation should be treated as such, or as branch value (and be visually moved when re-rooting).

**Comment by meren** [comment]
You are the best, Florian! Thank you for providing an example here and helping Mete with this :)
