### ISSUE TITLE
[FEATURE REQUEST] Organize contigs by length in interactive interface

### ISSUE THREAD

**Issue by mschecht** [merenlab/anvio#2100]
## The need

Organizing contigs by continuous and categorical variables is super helpful when investigating sequences genomes and metagenomes. It would be great if the interactive interface could organize contigs by sequence length.

## The solution

I don't have experience with the front end of the interactive interface, but it would be great if sequence length could be accessed in the items-order drop-down menu.

## Beneficiaries

Anvi'o users who are exploring sequences in the interactive interface

## How to reproduce:

```
cd INFANT-GUT-TUTORIAL 

anvi-interactive -c CONTIGS.db -p PROFILE.db
```

I circled in red the length continuous variable and point to where it could be in the items-order dropdown menu. 

![image](https://github.com/merenlab/anvio/assets/8404575/21048201-c7d0-4699-9adc-148cdc093540)

Thanks for your consideration!

**Comment by meren** [comment]
The commit af1ebd70e639d891ed87bb99d983e1c71e52aee5 solves this issue. 

Here is an example with the IGD (data layers are removed for simplicity).

This is the default items order based on "Seq. Composition + Diff Coverage":

![image](https://github.com/merenlab/anvio/assets/197307/2cb37c91-8e6e-4e3f-80c2-14e19b163f75)

And this is when one selects the new item order called `<> Length` which should appear in the items order menu after this commit:

![image](https://github.com/merenlab/anvio/assets/197307/afcd7bdc-7ff6-4194-a781-88f10a4e3905)

The algorithm is smart and orders items by keeping in mind the length of their parents (rather than merely ordering 'splits' based on their lengths). For projects with long contigs, the length order will not break the connection between splits. It shouldn't matter for projects with shorter contigs (i.e., EcoPhylo outputs, tRNA-seq displays, etc).

**Comment by meren** [comment]
@mschecht, please make sure it is working well for you, and close the issue if there are no problems.

**Comment by mschecht** [comment]
@meren I tested this on IGD and my own data and it's performing as expected!

![image](https://github.com/merenlab/anvio/assets/8404575/2e1da8b5-233f-4a9e-8773-45445022bd53)

Thanks for the help!
