### ISSUE TITLE
No "load bin collection" button

### ISSUE THREAD

**Issue by magueos** [merenlab/anvio#2178]
## Short description of the problem

anvio interactive interface does not have the "load bin collection" button
## anvi'o version

anvio-8
```
anvi-self-test --version
```

## System info

I am using linux as OS and the program was installed by following the instructions of the website

## Detailed description of the issue

I am trying to curate some bins from my metagenomic data and everything seems to work good. In order to curate them I am using the command line "anvi-refine":

anvi-refine -c Pul_bin_contigs.db -p ./Pulque/PROFILE.db -C PulMETATOR -b MetaTOR_4_1

but the button "load bin collection" from the bins sections is not showing up, as well as the store bin collection. All I have is "Load state" / "Save state"

I am following your tutoral https://merenlab.org/2017/01/03/loki-the-link-archaea-eukaryota/  so I dont know if there is something wrong with this interface or if its an actualization from the program

## Files / commands to reproduce the issue

Having reproducible files can help us a lot to fix an issue. So please consider sharing with us files to reproduce the issue (i.e., a contigs database, a profile database, an input file, a BAM file, etc).

Put them in a single directory, compress the directory, upload it to Dropbox (or any other comparable service), and replace the text here with with a direct download link along with instructions, such as exact command line instructions, on how to reproduce the error.

If you don't have files to share, please remove this section along with the header.

**Comment by meren** [comment]
The interface changed quite a bit since those times. `anvi-refine` does not have a load / save bin collection buttons anymore. Instead, it has this:

<img width="468" alt="image" src="https://github.com/merenlab/anvio/assets/197307/b45a56bf-5912-4bc4-a4ea-f1c9dd790057">

Once you are satisfied with your selections, you use that button to split the bin(s) being refined as new bins based on your selections. Any contig that is not selected into a bin prior to that is discarded and not included in any bin.
