### ISSUE TITLE
Creating a Bin_XXX_profile.db from a master profile.db

### ISSUE THREAD

**Issue by tdelmont** [merenlab/anvio#289]
Hi, 
I know, Meren will kill m for this issue, but I think we need this capability moving forward:
If only the bin_XXX is of interest from a large assembly, it would be great to create a bin_XXX_contig.db and bin_XXX_profile.db (and SNVs file also I assume) containing only information from associated splits. This would help sharing critical information to collaborators, and for bin specific submissions (e.g., in NCBI).

Tom

**Comment by meren** [comment]
This is not too hard to do, the real problem is probably I am the only one who can do that in reasonable amount of time, otherwise this could be a very sweet little project for someone else.

Essentially it requires the relevant information for splits represented in the bin of interest to be extracted from the merged/single profile database and stored in a new one.

**Comment by meren** [comment]
Well, good job Meren. Finally I found an issue that is already resolved :)

`anvi-split` does this.
