### ISSUE TITLE
Convert TAB-delimited metadata into anvi'o

### ISSUE THREAD

**Issue by cascoamarillo** [merenlab/anvio#355]
Convert TAB-delimited metadata (BED files, GFF files) into another TAB-delmited metadata with the proper split names, so it can be used with anvi-interactive -A.

**Comment by meren** [comment]
Hi @cascoamarillo,

I am very sorry, but I *just* saw this report!! :/

If it is not too late, can you please elaborate what exactly it is you need? If you can send an example I can start thinking about it.

Sorry again!

Best,

**Comment by cascoamarillo** [comment]
Hi Meren,
No prob. He he. As you requested me on our http://merenlab.org/2015/05/02/anvio-tutorial/ conversation, I entered this issue. The idea is to be able to convert a tab-delimited file (it can be a gff or not); like contig# - start - stop - feature, into another which shows correlation with the splitted contigs on anvio (contig#_split# - start - stop - feature) and at the end in can be incorporated with the -A option into anvi-interactive. Thanks

**Comment by meren** [comment]
Oh. Great. Now everything is slowly coming back to me. Sorry. The old age is killing me.

In order to implement this feature I will need some test data. In an ideal world, the test data would be for our `mini_test` (i.e., for this FASTA file: https://github.com/meren/anvio/blob/master/tests/sandbox/contigs.fa). 

Do you think you can help me get my hands on an example TAB-delimited file (GFF and/or any other format) for those contigs?


Best,

**Comment by cascoamarillo** [comment]
Here is an example of gff file derived from these contigs. Sorry, the github thing is too complicated for me : /

##gff3
204_10M_MERGED.PERFECT.gz.keep_contig_878	.	gene	1000	9000	.	+	.	ID=gene00001
204_10M_MERGED.PERFECT.gz.keep_contig_878	.	gene	19000	21000	.	+	.	ID=gene00002
204_10M_MERGED.PERFECT.gz.keep_contig_878	.	gene	25000	28000	.	+	.	ID=gene00003
204_10M_MERGED.PERFECT.gz.keep_contig_6515	.	gene	5000	7500	.	-	.	ID=gene00004
204_10M_MERGED.PERFECT.gz.keep_contig_1720	.	gene	666	1111	.	-	.	ID=gene00005
204_10M_MERGED.PERFECT.gz.keep_contig_1720	.	telomere	12000	16856	.	+	.	Name=Motif:(CCCACA)n
