### ISSUE TITLE
--min-contig-length argument in anvi-profile (default value)

### ISSUE THREAD

**Issue by ekiefl** [merenlab/anvio#523]
It is confusing to me why the default value for `--min-contig-length` in `anvi-profile` is set to the arbitrary number 2500. Maybe this should be set to 0 by default. The reasoning is that when users create a contigs.db, they should be trusted that the fasta file they provide contains only the contigs they are interested in. If they need to curate their contigs prior to `anvi-gen-contigs-database`, they should do so with `anvi-script-reformat-fasta` (it has the flag `--min-len` to filter by contig length). Alternatively, if for some reason they want to curate their contigs after `anvi-gen-contigs-database`, they can provide the `--min-contig-length` in `anvi-profile`, but they shouldn't have to specify that they _don't_ want to filter their contigs.

**Comment by meren** [comment]
Everything you are suggesting is correct, but the default value is necessary, and here is why:

If users were to read tutorials and/or help menus of programs they use, they would have already known that there is a default cutoff to avoid days of computation and utilization of plethora of disk space for tiny tiny contigs that will not be used anyway. With a default of `2,500` the damage is contained: If they don't read, *and* end up getting their short but important contigs lost because of that, it will be a quick recovery and it will affect only one person. In contrast, if the default is `0` nts, and they proceed to profile all contigs in an assembly because they haven't read, it will be a major depletion of scarce resources until they figure out something is wrong, and it will affect many people.

In a sense, by setting an arbitrarily cutoff that may not be suitable for specific projects, we are being responsible and protect everyone who have to share scare resources with users who don't have time to read the fine print.

The world owes us.
