### ISSUE TITLE
Minimum mean coverage for reporting MAGs?

### ISSUE THREAD

**Issue by adityabandla** [merenlab/anvio#525]
Hi

Apart from C/R estimates, any rule of thumb estimates for the minimum mean coverage of contigs, for refining and reporting MAGs?

Further, is there a way to compute the cumulative coverage for contigs, instead of coverage on a per sample basis?

Best,
Aditya

**Comment by meren** [comment]
Hi Aditya,

Although it is never clarified anywhere, I think the anvi'o discussion group is a much better revenue to discuss opinions and/or best practices rather than GitHub issues section. In contrast to the anvi'o discussion group, GitHub issues are better to handle technical issue related to codebase.

I hope you would consider sending this topic as a question to the discussion group, and closing this issue.

Best,

**Comment by adityabandla** [comment]
Thanks Meren, point taken!
