### ISSUE TITLE
"anvi-get-sequences-for-hmm-hits --align-with famsa" flag does not work with individual genes

### ISSUE THREAD

**Issue by rbartelme** [merenlab/anvio#601]
when running:

anvi-get-sequences-for-hmm-hits -e ext-genomes.txt --hmm-sources Campbell_et_al --gene-names GENE --get-aa-sequences --return-best-hit --align-with famsa -o GENE.fa

The resulting fasta file does not contain any "-" indicative of alignment, and the output sequence length varies. 

The alignment is normal when the concatenate flag is used.

**Comment by meren** [comment]
I should add a control for this. If you don't use --concatenate, there is no alignment. Why? Because I thought more often than not people would try to align sequences that are too irrelevant to each other. But limiting people like that is not the anvi'o way, and I will fix this by adding a warning that they may be doing something ridiculous, but it will not affect how much we like them.

Thanks,

**Comment by meren** [comment]
Hey Ryan,

I fixed this in the `assembly-view` branch, which is going to be merged into the `master` branch very soon. @ozcan has been working on that branch to implement something cool (as the name probably suggests), and we are planning to release a stable version very soon.

You can either checkout that branch to test this new addition (which will work perfectly with the command line you sent in your report), or you can wait for the official version which should only be a couple of days away.

**Comment by rbartelme** [comment]
Thanks @ozcan and @meren!

All these features sound really cool, interested to see what assembly-view has to offer. :)
