### ISSUE TITLE
stable v3 anvi-mcg-classifier matplotlib problem

### ISSUE THREAD

**Issue by AstrobioMike** [merenlab/anvio#603]
Hey there! 

I installed the stable v3 with virtualenv, passed the sweet mini suite test with no issues, but when i tried to look into this program i got a missing matplotlib error. Running pip in the virtualenv to install matplotlib installed a couple things, and then i got a new error message telling me python is not installed as a framework. The attached text file has the output of both. My OS is Sierra v10.12.6. 

Let me know if you need any other info from me if you think this is a problem on your end!
-mike

[matplot_error.txt](https://github.com/merenlab/anvio/files/1361293/matplot_error.txt)

**Comment by ozcan** [comment]
Hey @AstrobioMike,
Unfortunately matplotlib does not work with virtualenv in OSX, there are some workarounds mentioned [here](https://stackoverflow.com/questions/29433824/unable-to-import-matplotlib-pyplot-as-plt-in-virtualenv). If I remember correctly @ShaiberAlon solved this issue using [venv](https://docs.python.org/3/library/venv.html) instead of virtualenv, which we thought more straightforward solution than the other workarounds.

**Comment by AstrobioMike** [comment]
Ah, gotcha. Thanks for the quick response, Ozcan!

**Comment by ShaiberAlon** [comment]
I definitely recommend using venv. Comes builtin with python3, and solves
the problem.

Best,

Alon
