### ISSUE TITLE
Google Computing unable to make http connection

### ISSUE THREAD

**Issue by bigsuiparty** [merenlab/anvio#619]
Hey there,

I am trying to use anvi'o 3 via a Google Computing VM. 
When I try to use anvi-display-contigs-stats [my-database], I get the following error:

Looking up 0.0.0.0:8080
Making HTTP connection to 0.0.0.0:8080
Alert!: Unable to connect to remote host.
lynx: Can't access startfile http://0.0.0.0:8080/
* The server is now listening the port number "8080". When you are finished, press
CTRL+C to terminate the server.

Is there a way to make this work?

Cheers

**Comment by meren** [comment]
Hi,

You can set the IP address of your VM to run the server through that address instead of `0.0.0.0`. 

Also, you probably are going to try to connect from a client, and you should only run the server with the flag `--server-only`, so anvi'o does not try to show you the page with lynx :)

If you succeed in running anvi'o via GCVM, I would be very very happy to hear your experience, and maybe put together a little tutorial for others because this is one of the questions we occasionally get.


Best wishes,

**Comment by bigsuiparty** [comment]
Hey!

I was able to get it to work with a few firewall manipulations and setting up VNC viewer for GUI..

Since I am new to Google Computing VM as well as anvi'o everything takes time to figure out. Nonetheless, aside from a few speed bumps everything seems to work out until now. If you want we can communicate again when I have everything set up. A tutorial would likely help alot of people as Google Computing seems to become more and more relevant for people with limited ressources.

Best wishes

**Comment by meren** [comment]
That would be excellent to communicate again when you have everything set up! Meanwhile, please keep us posted if you need more from us.
