### ISSUE TITLE
Processing SAAVs on predefined coordinates during anvi-profile

### ISSUE THREAD

**Issue by tdelmont** [merenlab/anvio#670]
Hi,

I had the chance to interact with various bioinformaticians at the Genoscope, France. They were very interested by the SAAV processing capabilities of anvi'o, and were considering applying it to their ongoing research, especially on the TARA Oceans metagenomes they are constantly producing. 

Yet, they would like to be in control of the SNV part (they have developed new approaches to identify SNVs from the assembly graph - unpublished).

Meren, do you think it would be possible to add the possibility of submitting a text file with SNV positions so that anvi-profile processes (SNVs and) SAAVs only on these positions?

It would add flexibility, and remove the burden of controlling SNV calling in times to come within the platform anvi'o.

I also realize this represents extra coding work....

Best,

Tom

**Comment by meren** [comment]
It is currently possible for people who have programming expertise to do it by manipulating the `variable_nucleotide_positions` table in anvi'o profile databases. While this would immediately impact inspection and summary, it will not affect the SAAV processing.

Scrutinizing SAAV positions to those that are listed in the SNV table is not going to truly affect anything either, since anvi'o needs to work with the actual BAM file to identify frequencies of individual codons at positions of variation. A better approach would be to give the SNVs prior to profiling, which would require @ozcan or I to change the profiler. Although we could do that, this will not result in more accurate SAAVs. SNVs will tell anvi'o to take a look at a given position to process SAAVs with a larger context, but then the raw data will dictate codon frequencies, making it irrelevant to SNVs.

The right way to do this is to edit/modify BAM files by removing reads that are not coming from contexts of the assembly graph from which the SNV frequencies are profiled. There would be two sets of BAM files for every sample, one to profile SNVs and SAAVs based on reads *mapped to the assembly graph*, and another to profile all reads coming from the mapping results. Other options are ad hoc and error-prone.

**Comment by tdelmont** [comment]
Hi,

Your suggestion of giving the SNVs prior to profiling is in fact what I tried to formulate. 

Also, I am not implying that providing the SNVs would "result in more accurate SAAVs". Simply, some people are already working with their own SNV matrix, and would like to determine SAAVs without changing their SNV analysis. Indeed, the raw data stored in the BAM would then dictate codon frequencies. 

As a last clarification, these researchers have their own way to identify SNVs from the graph. Now, they would like to use the identified SNV positions and anvi'o to determine SAAVs in pre-defined contig coordinates.

Improving the flexibility of anvi-profile would be fantastic for their research goals.

Tom
