### ISSUE TITLE
anvi-get-aa-sequences-for-gene-calls and anvi-get-dna-sequences-for-gene-calls should be one program

### ISSUE THREAD

**Issue by tdelmont** [merenlab/anvio#719]
Hi,

It would be great to add the flag "**--report-extended-deflines**" in the program **anvi-get-aa-sequences-for-gene-calls**.

In fact, while available at the DNA sequence level this flag is not available when exporting AA sequences:

anvi-get-aa-sequences-for-gene-calls --report-extended-deflines -c Asgard_17_MAGs_CONTIGS.db -o AA.fasta
usage: anvi-get-aa-sequences-for-gene-calls [-h] -c CONTIGS_DB [-o FILE_PATH]
                                            [--gene-caller-ids GENE_CALLER_IDS]
                                            [--delimiter CHAR] [--version]
                                            [--debug]
anvi-get-aa-sequences-for-gene-calls: error: unrecognized arguments: --report-extended-deflines

Thanks for considering this point,

Tom

**Comment by meren** [comment]
The best way to resolve is to solve this mess. Which requires me and @ozcan to think of a better design. Currently there are two programs `anvi-get-aa-sequences-for-gene-calls` and `anvi-get-dna-sequences-for-gene-calls`. It would have been better to have a single program, `anvi-get-sequences-for-gene-calls` which accepts a flag for `--get-aa-seqeunces`.

This is not the case due to a poor design somewhere in the dbops (thanks, Obama).

I will leave this for later for us to take a look and redesign.

**Comment by meren** [comment]
They are now :)
