### ISSUE TITLE
anvi-summarize fails to recover split names for bins when working with blank profiles

### ISSUE THREAD

**Issue by nohayoussef** [merenlab/anvio#769]
Hi,
First thanks for a wonderful program. 
I have been trying to bin without mapping (no BAM file) on my contigs.fasta.
Everything seems to work fine and I am able to assign bins after anvi-interactive. I know my bins are stored from the output of anvi-show-collections-and-bins and also anvi-script-get-collection-info.

The problem is that I don't see bins when I summarize.
When I try to anvi-summarize, I get the warning:
"Some of the bins in this collection (precisely 2 of 0 total) did not contain any
that appeared in the profile database. There are multiple reasons for why this
can happen. But one of the common scenario could be this: You imported an
external collection, and some of the bins you have in that collection contain a
small number of contigs that were too short to make it into the merged profile.
Well, if you would like to figure out what might be the scenario for your
experiment, here is the list of bin names that did not go through: Bin_1, Bin_2."

I have tried to profile with minimum length 1500 instead of 2500 and get the same warning either way. The summary url also shows this "Bins that were identified in the blank profile database 'Fraser' and stored in the database as "Fraser 1500" collection, describe None bins accountig for None nucleotides, which represent 0.00% of all nucleotides stored in the contigs database." 

Could you please help?
Thank you

**Comment by meren** [comment]
Would you mind sending your contigs.fasta through private e-mail to me (`a.murat.eren at gmail com`), and telling me step by step which commands did you use so I can recapitulate the error here?


Thanks,

**Comment by meren** [comment]
Thanks for the help, Noha.

It turns out that the error was due to an anvi'o bug that is now fixed.

The fix will be available in the next stable version (unless you want to [track the `master` repository](http://merenlab.org/2016/06/26/installation-v2/#installation-for-developers-youre-a-wizard-arry) (which is not a bad idea), or hack your installation to replace your `dbops.py` file to reflect the changes here: 3ec0140bf913b477209752c5ee1146e524c52d76 (which is a bad idea)).
