### ISSUE TITLE
Pangenome: IndexError: string index out of range

### ISSUE THREAD

**Issue by Derreckadam** [merenlab/anvio#791]
Hello,

I'm getting an error, halfway through my pangenome analysis, during the alignment. I was wondering if there was anyway to know which file specifically the aligner was on when it threw up the "IndexError: string index out of range"? All I know is that it was on aligning file 15810 of 19000 when it stopped last night. I assume this is an error with one of the genome files I downloaded from NCBI, but I was able to successfully create a contigs.db for all of them. 

Thanks!
Derreck 
![screen shot 2018-03-22 at 9 56 49 am](https://user-images.githubusercontent.com/17322331/37785464-7263dc92-2db7-11e8-81c5-313a975a75c0.png)

**Comment by meren** [comment]
It is very frustrating isn't it --when things stop right there close to the end. But the problem is probably due to something else that stays in the queue forever. You likely have weird genes with lots of N's in your genomes (a similar problem was due to that recently).

Nevertheless, we fixed this behavior in the `master` repository: https://github.com/merenlab/anvio/commit/54b3b3d12af5be3c6aaf73cbc86f17376d4ca128 (so anvi'o says "welp, I tried, but this gene cluster failed, moving on with the rest" instead of exploding like that).

It will take awhile to release `v5`, but we might release something quick rather soon. Meanwhile you can use the `--skip-alignments` flag to avoid this error and get your pangenome.
