### ISSUE TITLE
corresponding_gene_call and codon_orer_in_gene should be switched

### ISSUE THREAD

**Issue by ekiefl** [merenlab/anvio#802]
corresponding_gene_call should be switched to gene_callers_id for consistency with the rest of the code base.

I also feel that codon_order_in_gene should be switched to codon_index and pos should be switched to nt_index. The reason why I propose the suffix 'index' instead of 'pos' is because anvi'o goes against the grain by saying the position of the first methionine of a protein is 0. The rest of the field says it's 1, and well-traversed terminology depends on this convention. For example, K148R refers to a substitution of lysine to arginine at the 148th position (assuming methionine position is 1). By using the word index instead of position, people will hopefully realize what we're doing is unconventional. Alternatively we could adopt the terminology everyone uses, despite it being ugly to computer scientists.

The reason why I'm posting this as an issue is because database tables contain these names and so an upgrade script will be required. So it would be best to carry out these changes when we are close to releasing v5.

**Comment by meren** [comment]
I like `codon_index` more than `codon_order_in_gene`, and I like the use of `index` instead of `pos` for the reason you mention. Maybe while we are doing this we can also fix another associated issue: we have `pos` and `pos_contig`. In the new terminology they should be `nt_index_split` and `nt_index_contig`.

>  what we're doing is unconventional

💔
