### ISSUE TITLE
can't install errors appear

### ISSUE THREAD

**Issue by JulianMarchesi** [merenlab/anvio#820]
Hi

I am not a computer scientist with limited linux experience. But tried to install anvio using the homebrew route and got this

```
Tapped 160 formulae (193 files, 453.3KB)
Error: Calling 'depends_on ... => :perl' is disabled!
There is no replacement.
/home/linuxbrew/.linuxbrew/Library/Taps/tseemann/homebrew-bioinformatics-linux/Formula/roary.rb:11:in `<class:Roary>'
Please report this to the tseemann/bioinformatics-linux tap!
Or, even better, submit a PR to fix it!
If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/tseemann/homebrew-bioinformatics-linux/issues
```

Any suggestions?

cheers

Julian

**Comment by meren** [comment]
Hi Julian,

Why not reporting it to https://github.com/tseemann/homebrew-bioinformatics-linux/issues as the error suggests?


Best,

**Comment by meren** [comment]
Just realized that it is still here. Sorry about your frustration, @JulianMarchesi 

> What does this mean??? “Or, even better, submit a PR to fix it!”
> 
> What’s a PR?

PR means "pull request" and it is something that is only expected of computer scientists if they have time an energy. Through PRs, you can suggest changes in someone's code. I.e., you would download their broken code, fix it by going through it, and then send your changes to them through a _PR_.

> I seem to waste more time trying to get things working than actually working.

I totally understand this and I feel personally responsible for making people waste time while desperately trying to make bioinformatics solutions work for them. The main problem is most people who produce these solutions are doing it in their spare time, without supported by any funding, and by taking time from their family and actual science in an attempt to make tools they develop for their own research accessible to others.

It is not an excuse, of course. But there is no easy solution for it either.

But here is a sincere and serious suggestion: if you take your computer and fly to Chicago to visit us at the University, I promise we will make anvi'o work on your computer with all the bells and whistles, then we will take you out for a dinner in for the best food money can buy in Hyde Park, and then send you back home after a good bit of jet-lag.

Send me an e-mail to set the date if you are interested.

Otherwise wait for the version `v6` of anvi'o we will release soon if you are still interested in giving anvi'o a chance. We are determined to put together an easy-to-follow installation instruction, and it would be great to see if that could make things work on your computer.

**Comment by meren** [comment]
@JulianMarchesi,

I just realized that we haven't responded to this issue for all this time. Sorry about that, and sorry about your frustration.

> What does this mean??? “Or, even better, submit a PR to fix it!”
> 
> What’s a PR?

PR means "[pull request](https://git-scm.com/docs/git-request-pull)" and it is something that is often expected only of compute-savvy people. In a nutshell, through PRs one can suggest particular changes in someone's code. I.e., you would download their broken code, fix it by carefully going through it, and then send your proposed changes to them through a _PR_. It is a lingo commonly used by `git`, which is the most popular version control system used commonly by those of us who develop open-source software.

> I seem to waste more time trying to get things working than actually working.

I totally understand this and I feel personally responsible for making people waste time while desperately trying to make bioinformatics solutions work for them. The main problem is most people who produce these solutions are doing it in their spare time, without supported by any stable funding for it, and often by taking time from their family and actual science in an attempt to make the tools they actually develop for their own research, accessible to others.

It is not an excuse, of course. But there is no easy solution that addresses both your and our problems at the same time, either. But here is a sincere and serious suggestion to address at least your problem: if you take your computer and fly to Chicago to visit us at the University, I promise we will make anvi'o work on your computer with all the bells and whistles, then we will take you out for a dinner in for the best food money can buy in Hyde Park, and then send you back home after a good bit of jet-lag. Send me an e-mail to set the date if you are interested.

Otherwise, if you are still interested in giving anvi'o a chance, wait for the anvi'o version `v6`. We hope to release very soon and are determined to put together an easy-to-follow installation document. If that doesn't make things work on your computer we can go from there.

Best wishes,
