### ISSUE TITLE
--gene-view hangs in profile v27 master

### ISSUE THREAD

**Issue by ekiefl** [merenlab/anvio#843]
Running `anvi-interactive  -p 06_MERGED/SAR11/PROFILE.db -c 03_CONTIGS/SAR11-contigs.db --gene -C DEFAULT -b EVERYTHING` leads to a hang after clicking 'Draw' in the interface. I only observe the problem using --gene-view. Working directory sent in github channel

![image](https://user-images.githubusercontent.com/8688665/40928866-6d1e1bec-67e8-11e8-939e-67dea9a269d0.png)

**Comment by ozcan** [comment]
I found a workaround this but I need @ShaiberAlon and @meren's input. Since we switched newick format now if label part of the newick is numeric, interface thinks it is a branch support value instead of label. In gene mode leaf names are all numeric, we need to decide some prefix like `Gene_Callers_Id_X`.

**Comment by meren** [comment]
Dammit :( I knew one day assigning integer values as IDs for our gene calls would come to this.

Let's have an offline conversation about this and then summarize our decision here.
