### ISSUE TITLE
anvi-get-aa-sequences-for-gene-calls errors

### ISSUE THREAD

**Issue by asauk** [merenlab/anvio#855]
Hello, 

I am running anvi'o 2.4.0 on the Compute Canada cluster and I'm getting the attached error when no gene caller ids are specified. It gives me an output of aa sequences for the gene calls put some are missing according to the error. 

<img width="569" alt="anvio error" src="https://user-images.githubusercontent.com/40121508/41193007-e89dcde0-6bd4-11e8-8995-26f612171f5b.png">

I only want specific aa sequences relating to specific scaffolds so I tried to specify gene call ids but I get a unrecognized argument error. 

anvi-get-aa-sequences-for-gene-calls -c PH3_Jul14_contigs.db -o PH3_Jul14_geneoutput.faa --gene-caller-ids 12847,12848,12849,12850,12851,12852,12853,12854,12855
usage: anvi-get-aa-sequences-for-gene-calls [-h] -c CONTIGS_DB [-o FILE_PATH]
anvi-get-aa-sequences-for-gene-calls: error: unrecognized arguments: --gene-caller-ids 12847,12848,12849,12850,12851,12852,12853,12854,12855

I'm not sure if this an anvi'o problem or a problem with how I'm inputting the gene caller ids. If it's me, an example of how to input these correctly would be appreciated. 

Thank you, 

Alexandra

**Comment by meren** [comment]
Hi Alexandra,

That is a warning and it's OK.

Please switch to anvi'o `v4` as `2.4.0` is obsolete.

**Comment by meren** [comment]
Just to elaborate a bit more, I think the reason `--gene-caller-ids` is not working is because it is a parameter added in later versions of anvi'o, and is not available in `v2.4.0` :/

We made the mistake of not having tutorials for each version separately, which creates issues if people are using older versions of anvi'o and following our tutorials that are crafted only for the latest version :/

@ozcan and I are planning to change that, but currently, this is the situation. And `v2.4.0` is really old for a rapidly developing platform. If you just look at the release notes for newer versions you can make a case to have anvi'o updated on the cluster:

https://github.com/merenlab/anvio/releases

Best,

**Comment by meren** [comment]
Wait. Why do you have ~7,000 gene calls without any sequences?

Can you explain how did you generate your contigs database step by step? Did you use external gene calls?

**Comment by asauk** [comment]
Thanks for the explanation. Graham isn't the best when it comes to updating anvi'o unfortunately, usually runs into a dependency issue (recently it's panda). 

I'm not sure how the contigs database was generated as that was done by my PI. 

The command output is:

sqlite3 PH3_Jul14_contigs.db 'select * from self'
version|8
db_type|contigs
contigs_db_hash|b69ea58d
split_length|20000
kmer_size|4
num_contigs|92890
total_length|494749038
num_splits|93479
gene_function_sources|
genes_are_called|1
splits_consider_gene_calls|1
creation_date|1507571641.28276
taxonomy_source|default_matrix

**Comment by meren** [comment]
OK. Nothing looks out of the ordinary.

Sorry to hear you have upgrading issues :/

**Comment by asauk** [comment]
Thanks for checking and for your help!
