### ISSUE TITLE
Anvi'o v5.1: fix_functional_occurence_table.py script trouble

### ISSUE THREAD

**Issue by mkhall** [merenlab/anvio#903]
I'm having some trouble with using the script fix_functional_occurence_table.py. I tried copying and pasting the line in the tutorial, replacing the given file names with my own (./fix_functional_occurence_table.py Thiomonas_COG_occurrence-fixed-a-little.txt Thiomonas_COG_occurrence-fixed.txt), but it just tells me "-bash: ./fix_functional_occurence_table.py: No such file or directory". It occurred to me that I might need to provide the file path of the script, but I can't seem to find it. I tried "find / -name "fix_functional_occurence_ta..." -type f -print", but I only got a bunch of 'permission denied' errors, as well as a few 'operation not permitted' and 'not a directory'. Is there something I'm missing here?

**Comment by ShaiberAlon** [comment]
Hi @mkhall, it seems to me that you are right, you must provide the path to the python script in order to use it. If you follow these steps (which I'm copying from this [section of the pangenomic tutorial](http://merenlab.org/2016/11/08/pangenomics-v2/#generating-an-anvio-genomes-storage)):

```bash
wget https://ndownloader.figshare.com/files/11857577 -O Prochlorococcus_31_genomes.tar.gz
tar -zxvf Prochlorococcus_31_genomes.tar.gz
cd Prochlorococcus_31_genomes
```

Then you should have a folder `Prochlorococcus_31_genomes` which contains this python script.
can then copy it to wherever you want and give the relevant path when you want to use it.

Alternatively, you can email me: alon.shaiber@gmail.com and I will send you this python file. You

**Comment by mkhall** [comment]
It worked! Thank you so much!
