### ISSUE TITLE
sporadic I/O error 

### ISSUE THREAD

**Issue by Lzinke** [merenlab/anvio#915]
Hi anvi'o gurus,

I am running anvi'o v4 on an HPC, here's the self-test:
Anvi'o version ...............................: 4
Profile DB version ...........................: 23
Contigs DB version ...........................: 10
Pan DB version ...............................: 8
Genome data storage version ..................: 6
Auxiliary data storage version ...............: 2

I having an issue where multiple commands will stop with an I/O error:
sqlite3.OperationalError: disk I/O error

I attached some text files with the anvi-script-FASTA-to-contigs-db command run on the same file, with errors happening in different places during the process (i.e. while running HMMs, while generating the contig database, and while calling ORFs). Usually if I rerun the command enough it will work. 

Any insights? 

Thanks!
[anvio_error_example3.txt](https://github.com/merenlab/anvio/files/2211705/anvio_error_example3.txt)
[anvio_error_example2.txt](https://github.com/merenlab/anvio/files/2211706/anvio_error_example2.txt)
[anvio_error_example1.txt](https://github.com/merenlab/anvio/files/2211707/anvio_error_example1.txt)

**Comment by sutterjlynn** [comment]
Hey Lzinke and Anvi'o folks, 

I just wanted to jump in here because I'm having a very similar problem. Using the latest conda install of Anvi'o (anvio 4.0.0) I get the following error when running the following script:

$anvi-gen-contigs-database -f Bacteroides_fragilis_2334.fa -n test_project -o test.db

Input FASTA file .............................: /tmp/global2/jsutter/anvio/AnvioPhylogenomicsTutorialDataPack/distantly-related/Bacteroides_fragilis_2334.fa
Name .........................................: test_project
Description ..................................: No description is given


Traceback (most recent call last):
  File "/ebio/abt3_projects/PseudoGenomes/miniconda3/envs/anvio_reinstall/bin/anvi-gen-contigs-database", line 50, in <module>
    a.create(args)
  File "/ebio/abt3_projects/PseudoGenomes/miniconda3/envs/anvio_reinstall/lib/python3.5/site-packages/anvio/dbops.py", line 2600, in create
    self.touch()
  File "/ebio/abt3_projects/PseudoGenomes/miniconda3/envs/anvio_reinstall/lib/python3.5/site-packages/anvio/dbops.py", line 2470, in touch
    self.db = db.DB(self.db_path, anvio.__contigs__version__, new_database=True)
  File "/ebio/abt3_projects/PseudoGenomes/miniconda3/envs/anvio_reinstall/lib/python3.5/site-packages/anvio/db.py", line 46, in __init__
    self.create_self()
  File "/ebio/abt3_projects/PseudoGenomes/miniconda3/envs/anvio_reinstall/lib/python3.5/site-packages/anvio/db.py", line 69, in create_self
    self._exec('''CREATE TABLE self (key text, value text)''')
  File "/ebio/abt3_projects/PseudoGenomes/miniconda3/envs/anvio_reinstall/lib/python3.5/site-packages/anvio/db.py", line 169, in _exec
    ret_val = self.cursor.execute(sql_query)
sqlite3.OperationalError: disk I/O error

Is there any known way to address this? I've tried downgrading python and sqlite to versions that worked back when I set up Anvi'o originally (when it worked) but to no avail. Thanks!

**Comment by meren** [comment]
The latest version of anvi'o is 5.2 :)

**Comment by sutterjlynn** [comment]
Hi Murat, 

Good to know, thank you! Despite getting everything up to date, Anvi'o still throws the same error. However, I just got it to run on our SGE cluster so it's probably an sql permissions issue on my lab's local server (@Lzinke, if it helps it all). Better than nothing!

**Comment by pbordron** [comment]
Hi same problem on our cluster. Seems related to the fact that sqlite has problem with database on NFS share.
https://stackoverflow.com/questions/29244788/error-disk-i-o-error-on-a-newly-created-database

**Comment by meren** [comment]
Hey everyone. Clearly we couldn't produce anything useful for you. Apologies.

**Comment by cssulliv** [comment]
Hi,

I am getting the same sqlite error when I run anvi-gen-contigs-database using Anvio v5.5 on our university cluster. It still generated .db files but am cautious to move forward after seeing the error. I wonder if anyone else is has this issue? 

Also, I installed Anvio using the following script.

`conda create -p apps/path/on/cluster/anvio5 python=3.6`
`conda install -p apps/path/on/cluster/anvio5 -c bioconda -c conda-forge anvio=5.5.0.`

I also get the following result after running `anvi-self-test -v`

```
Anvi'o version ...............................: margaret (v5.5)
Profile DB version ...........................: 31
Contigs DB version ...........................: 12
Pan DB version ...............................: 13
Genome data storage version ..................: 6
Auxiliary data storage version ...............: 2
Structure DB version .........................: 1
```

I'd run the re-analysis on my local computer, which has a working Anvio v 5.5 but its computationally too heavy. 

Any suggestions?

Mahalo!
