### ISSUE TITLE
parallel runs of anvi-run-hmms cause race conditions during database write

### ISSUE THREAD

**Issue by meren** [merenlab/anvio#922]
We need a creative solution to avoid this (related issue #917).

**Comment by ozcan** [comment]
We can implement this in library layer and ask SQLite if the database is open anywhere else (checking the presence of `.journal` file basically)

Also, we can implement this at the application layer and keep a flag in `self` table like `write_protected` and every time we populate tables we can set the flag and commit first. After we are done, we can unset it. There will be times this flag will be set wrongly and we can use `--force` flag to ignore it after warning the user about consequences.

I would like to implement something more complex than these solutions, that allows parallel writing instead of avoiding conflict but that would require much more investment. 

I am open to feedbacks about these solutions

**Comment by meren** [comment]
I like the idea of using the `.journal` file to make sure we avoid parallel write operations. 

We could add a global parameter, i.e., `--enforce-db-write`, like `--debug` or `--version`, so if it is declared our library-level check would ignore. I think your first option is a good one.

**Comment by kkpsiren** [comment]
Any updates on this? I just managed to do wreck few contigs.db as described in (related issue #917). Now I am afraid to do more than 1 operation at a time to a .db.
