### ISSUE TITLE
problem identifying the correct domain using hmms

### ISSUE THREAD

**Issue by tdelmont** [merenlab/anvio#941]
Hi!

using anvi'o v5.1 here.

I am working with eukaryotic SAGs, and while in most cases anvi'o identifies them as eukaryotes, in at least one occasion anvi'o got it wrong, which is fine, but the patterns suggest it should have been right.

Here it is:

```
Source     SCG domain     Percent completion     Percent redundancy
BUSCO 83 Protista     eukarya     63.86%     8.43%
Rinke et al     archaea     72.22%     101.85%
Campbell et al     bacteria     79.86%     121.58%
```
The selected Domain was Bacteria, with confidence of -0.42.

Thanks a lot for looking into this,

Tom

**Comment by meren** [comment]
There is no easy way of solving this :( But I will look into this again.

**Comment by ShaiberAlon** [comment]
@meren, I was observing some weird behavior during refine right now, and I wonder if it is related to this:
I removed a single contig and saw that completion went _**UP**_, and after being very confused, I realized that went from using Rinke et al to using Campbell et al. But why was Rinke et al used to begin with? since the completion with Campbell et al was much higher (>25% vs. <10%).

**Comment by meren** [comment]
My recent changes in f4d902ebe02eb7e891f29b6c18f601c3da44bd85  screwed this up. 

I think it could be about this line not functioning the way it should have after other changes:

https://github.com/merenlab/anvio/commit/f4d902ebe02eb7e891f29b6c18f601c3da44bd85#diff-cca19f0c3d2bdca428083d6dd9cb83bcL146

Unfortunately it will take some time for me to get back to this, so anyone code-savvy should feel free to play with ti.

**Comment by meren** [comment]
@ShaiberAlon, can you please confirm that this now works for you?

**Comment by ShaiberAlon** [comment]
Hi Meren, I used my example to check this, and it looks good! Thank you!
