### ISSUE TITLE
Workflow for combining metagenomics/transcriptomics data for different time points

### ISSUE THREAD

**Issue by johanneswerner** [merenlab/anvio#953]
How do I have to adapt the combined metagenomics/transcriptomics workflow if my data has the following format: 

1 metagenome (to be precise, actually not a co-assemly) 
and 5 metatranscriptomes for 5 different time points?

How can I adapt the workflow? In particular, I would like to obtain a table-like structure (metatranscriptome samples vs gene/protein names with transcripts per million values. 

Do you have any ideas? Thank you very much for your good work.

**Comment by meren** [comment]
Hi @johanneswerner,

A workflow like this could be useful:

* Generate your contigs database from the assembled metagenome,
* Map all DNA and RNA reads to generate single profiles and merge them (using `--skip-hierarchical-clustering` and `--skip-concoct-binning` flags when runnig `anvi-merge`, since you do not want to use transcriptomic data to be used for differential coverage),
* Add a default collection with `anvi-script-add-default-collection` to your merged profile database, * Then use `anvi-summarize` on the collection you just generated in the step before using `-C DEFAULT`, and use the `--init-gene-coverages` flag to make sure you have gene coverage values across your metagenome and metatranscriptomes. 

You will find everything you need in the anvi-summarize output.


Best,
