### ISSUE TITLE
Hierarchical clustering failed for cov, tnf, tnf-cov

### ISSUE THREAD

**Issue by gelomerase** [merenlab/anvio#992]
Hi,

Using version 5.1 and the metagenomics workflow:

It's my first time to use anvio. I get the following messages when I am running anvi-merge step

`[21 Sep 18 09:08:54] 
* Anvi'o hierarchical clustering of contigs...

[21 Sep 18 09:09:36] 
WARNING
===============================================
Clustering has failed for "cov": "got differing extents in dimension 0 (got
116589338 and 2264072986)"

[21 Sep 18 09:17:15] 
WARNING
===============================================
Clustering has failed for "tnf": "got differing extents in dimension 0 (got
116589338 and 2264072986)"

[21 Sep 18 09:27:44] 
WARNING
===============================================
Clustering has failed for "tnf-cov": "got differing extents in dimension 0 (got
116589338 and 2264072986)"
`

It has proceeded to CONCOCT binning for quite some time now but I can't seem to find the same error in other sites so I thought to ask here. Is this normal? I am merging three samples for a single contigs.db on 24 cores and 300GB of memory.

Thanks!

**Comment by meren** [comment]
I don't think we can work with this report.

Please send entire outputs from `anvi-merge`.

**Comment by meren** [comment]
Until then I'll close this.

**Comment by Fedorov113** [comment]
I get this error too. Posting log file. 
[log.txt](https://github.com/merenlab/anvio/files/3084635/log.txt)

**Comment by meren** [comment]
Hey @Fedorov113,

This is from your log file:

```
WARNING
===============================================
Becasue you have used the flag `--enforce-hierarchical-clustering`, anvi'o will
attempt to create a hierarchical clustering of your 108,559 splits. It may take
a bit of time...
```

You have 100+K splits, which is way beyond the number of splits that can be processed with hierarchical clustering, but you are enforcing that analysis with the `--enforce-hierarchical-clustering`, and so the anvi'o fails because you do not have infinite amount of memory :)

Not necessarily an error. The next step for you is to import a collection for binning results you obtained from commonly used algorithms (such as `CONCOCT`, or `MetaBat`, or `MaxBin`, etc). Hopefully in `v6` we will streamline this process dramatically.

Apologies for the confusion.

**Comment by Fedorov113** [comment]
@meren Thank you for your reply! I suspected this, but just wanted to be sure.

**Comment by Fedorov113** [comment]
@meren I ran this step again on a node with more memory and everything worked fine. So this is indeed just a memory related issue. Thank you.

**Comment by meren** [comment]
Thank you very much for reporting back! :)

Now a different challenge awaits: visualizing that many items! :) I'm sure you will find a way if you've been getting used to the platform. Good luck with your research.
